name: Run All Bots (Parallel)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Self-healing setiap 6 jam

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Bot Matrix
        id: set-matrix
        run: |
          # Parse bots_config.json dan filter yang enabled
          MATRIX=$(jq -c '{bot: [.bots_and_tools[] | select(.enabled == true and (.path | contains("/privatekey/") or contains("/token/")))]}' config/bots_config.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "Generated matrix:"
          echo "$MATRIX" | jq .

  run-bots:
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 350
    strategy:
      fail-fast: false  # Jangan stop semua kalau 1 bot error
      max-parallel: 10   # Maksimal 10 bot parallel (sesuaikan dengan limit GitHub)
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    name: ${{ matrix.bot.name }}

    steps:
      - name: Setup Python
        if: matrix.bot.type == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Node.js
        if: matrix.bot.type == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone Bot Repository
        run: |
          echo "Cloning ${{ matrix.bot.name }}..."
          git clone --depth 1 "${{ matrix.bot.repo_url }}" bot

      - name: Install Python Dependencies
        if: matrix.bot.type == 'python'
        working-directory: bot
        run: |
          if [ -f "requirements.txt" ]; then
            pip install --no-cache-dir -r requirements.txt
          fi

      - name: Install Node Dependencies
        if: matrix.bot.type == 'javascript'
        working-directory: bot
        run: |
          if [ -f "package.json" ]; then
            npm install --silent
          fi

      - name: Run Bot
        working-directory: bot
        timeout-minutes: 340
        run: |
          BOT_TYPE="${{ matrix.bot.type }}"
          
          if [ "$BOT_TYPE" = "python" ]; then
            if [ -f "run.py" ]; then
              python run.py
            elif [ -f "main.py" ]; then
              python main.py
            else
              echo "ERROR: No Python entry point found"
              exit 1
            fi
          elif [ "$BOT_TYPE" = "javascript" ]; then
            if [ -f "index.js" ]; then
              node index.js
            elif [ -f "main.js" ]; then
              node main.js
            else
              echo "ERROR: No JavaScript entry point found"
              exit 1
            fi
          fi

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.bot.name }}
          path: bot/**/*.log
          retention-days: 3
          if-no-files-found: ignore
